#!/usr/bin/bash

if [ "${EUID:-$(id -u)}" -lt 1000 ]; then
  echo "Bazzite user setup ran as unsupported user. Exiting."
  exit 0
fi

IMAGE_INFO="/usr/share/ublue-os/image-info.json"
IMAGE_NAME=$(jq -r '."image-name"' < $IMAGE_INFO)
BASE_IMAGE_NAME=$(jq -r '."base-image-name"' < $IMAGE_INFO)
FEDORA_VERSION=$(jq -r '."fedora-version"' < $IMAGE_INFO)

SYS_ID="$(/usr/libexec/hwsupport/sysid)"
VEN_ID="$(cat /sys/devices/virtual/dmi/id/chassis_vendor)"

# INIT
BAZZITE_CONFIG_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/bazzite"
mkdir -p "$BAZZITE_CONFIG_DIR"

# SCRIPT VERSION
USER_SETUP_VER=43
USER_SETUP_VER_FILE="$BAZZITE_CONFIG_DIR/version"
USER_SETUP_FEDORA_VER_FILE="$BAZZITE_CONFIG_DIR/fedora_version"
USER_SETUP_IMAGE_VER_FILE=$BAZZITE_CONFIG_DIR/image_name""

if [[ -f "$HOME/.bazzite-configured" ]]; then
  mv -f "$HOME/.bazzite-configured" "$USER_SETUP_VER_FILE"
fi

if [[ -f "$HOME/.bazzite-configured-fedora-version" ]]; then
  mv -f "$HOME/.bazzite-configured-fedora-version" "$USER_SETUP_FEDORA_VER_FILE"
fi

# Run script if updated
if [[ -f $USER_SETUP_VER_FILE && -f $USER_SETUP_FEDORA_VER_FILE && -f $USER_SETUP_IMAGE_VER_FILE ]]; then
  USER_SETUP_VER_RAN=$(cat $USER_SETUP_VER_FILE)
  USER_SETUP_FEDORA_VER_RAN=$(cat $USER_SETUP_FEDORA_VER_FILE)
  USER_SETUP_IMAGE_VER_RAN=$(cat $USER_SETUP_IMAGE_VER_FILE)

  if [[ $USER_SETUP_VER = "$USER_SETUP_VER_RAN" && $FEDORA_VERSION = "$USER_SETUP_FEDORA_VER_RAN" && $BASE_IMAGE_NAME = "$USER_SETUP_IMAGE_VER_RAN" ]]; then
    echo "User setup v$USER_SETUP_VER has already run. Exiting..."
    exit 0
  fi
fi

# Handle privileged tasks
pkexec /usr/libexec/bazzite-privileged-user-setup "$USER"

if [[ $BASE_IMAGE_NAME =~ "kinoite" ]]; then
  echo 'Running setup for Kinoite'
else
  echo 'Running setup for Silverblue'

  echo 'Setting up templates'
  TEMPLATES_DIR=$(/usr/bin/xdg-user-dir TEMPLATES || true)
  if [[ -z "$TEMPLATES_DIR" || "$TEMPLATES_DIR" == "$HOME" ]]; then
    # xdg-user-dir might return only $HOME, in that case, use fallback $HOME/Templates.
    echo "Using fallback '$HOME/Templates'"
    TEMPLATES_DIR="$HOME/Templates"
  fi
  mkdir -p "$TEMPLATES_DIR"

  if [[ ! -f "$TEMPLATES_DIR/vkBasalt.conf" && -f "/etc/vkBasalt.conf" ]]; then
    ln -s "/etc/vkBasalt.conf" "$TEMPLATES_DIR/vkBasalt.conf"
  fi
  if [[ ! -f "$TEMPLATES_DIR/dxvk.conf" && -f "/etc/dxvk-example.conf" ]]; then
    ln -s "/etc/dxvk-example.conf" "$TEMPLATES_DIR/dxvk.conf"
  fi
  if [[ ! -f "$TEMPLATES_DIR/MangoHud.conf" && -f "/usr/share/doc/mangohud/MangoHud.conf.example" ]]; then
    ln -s "/usr/share/doc/mangohud/MangoHud.conf.example" "$TEMPLATES_DIR/MangoHud.conf"
  fi
fi

# Prevent future executions
echo "Writing state file"
echo $USER_SETUP_VER > $USER_SETUP_VER_FILE
echo $FEDORA_VERSION > $USER_SETUP_FEDORA_VER_FILE
echo $BASE_IMAGE_NAME > $USER_SETUP_IMAGE_VER_FILE
